@startuml
namespace core {
    class Battle << (S,Aquamarine) >> {
        + Pokemon1 *Pokemon
        + Pokemon2 *Pokemon

        + Start() string

    }
    class Move << (S,Aquamarine) >> {
        - randSource *rand.Rand

        + Name string
        + Power int
        + Accuracy int
        + Type string

        + CanHit() bool
        + CalculateDamage(attacker *Pokemon, defender *Pokemon) int

    }
    class Pokemon << (S,Aquamarine) >> {
        + Name string
        + HP int
        + Attack int
        + Defense int
        + Speed int
        + Moves []Move

        + AttackPokemon(target *Pokemon, move Move) (int, error)
        + IsFainted() bool

    }
}


@enduml
